name: Android Build

on: pull_request

jobs:

  build:
 
   runs-on: ubuntu-latest
 
   steps :
    
     - uses: action/main@v1

     - name: Setup JDK
       uses: action/setup-java@v1
       with:
            java version: 1.8

     - name: Run Tests
       run: ./gradlew test

     - name: Build Project
       run: ./gradlew assemble
